version: '3'
services:
  runner:
    image: golang:1.13
    volumes: 
      - .:/brucutu
    entrypoint:
      - tail 
      - -f 
      - /dev/null
  ssh:
    build: docker/ssh
    ports:
      - "2222:2222"
  email:
    build: docker/email
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./docker/email/dovecot.conf:/etc/dovecot/dovecot.conf 
      - ./docker/email/certificates/key.key:/etc/ssl/private/dovecot.key
      - ./docker/email/certificates/openssl.crt:/etc/ssl/certs/dovecot.crt
