services:
  runner:
    image: golang:1.21
    volumes: 
      - .:/brucutu
    working_dir: /brucutu
    entrypoint:
      - tail 
      - -f 
      - /dev/null
  ftp:
    image: fauria/vsftpd
    environment:
      FTP_USER: foo
      FTP_PASS: bar
      PASV_ADDRESS: 127.0.0.1
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

  httpd:
    build: docker/http_basic_auth
    ports:
      - "80:80"
      - "443:443"
  ssh:
    build: docker/ssh
    ports:
      - "2222:2222"
  email:
    build: docker/email
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./docker/email/dovecot.conf:/etc/dovecot/dovecot.conf 
      - ./docker/email/certificates/key.key:/etc/ssl/private/dovecot.key
      - ./docker/email/certificates/openssl.crt:/etc/ssl/certs/dovecot.crt
