version: '3'
services:
  runner:
    image: golang:1.12
  ssh:
    build: docker/ssh
    ports:
      - "22:22"
  email:
    build: docker/email
    ports:
      - "110:110"
      - "143:143"
    volumes:
      - ./docker/email/dovecot.conf:/etc/dovecot/dovecot.conf 
