version: '3'
services:
  runner:
    image: golang:1.12
    volumes: 
      - .:/brucutu
    entrypoint:
      - tail 
      - -f 
      - /dev/null
  ssh:
    build: docker/ssh
    ports:
      - "2222:2222"
  email:
    build: docker/email
    ports:
      - "110:110"
      - "143:143"
    volumes:
      - ./docker/email/dovecot.conf:/etc/dovecot/dovecot.conf 
