# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_repository: ~/repo
    steps:
      - checkout
      - run: make test
      - run: make build
  test:
    machine: true
    working_repository: ~/repo
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose exec runner bash -c "cd /brucutu && make test"
      - run: docker-compose exec runner bash -c "cd /brucutu && make integration"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
