# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    machine: true
    working_repository: ~/repo
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker-compose exec runner make test
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.12
   steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make test
      - run: make all